name: Swift test

# on:
#   pull_request:
#   push:
#     branches: master

on:
  workflow_call:

jobs:
  swift-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: .build
          key: ${{ runner.os }}-swift-test-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-swift-test-
      - name: Test
        shell: bash
        run: |
          set -o pipefail
          # TODO: xcbeautify when it properly formats swif-testing errors
          swift test --only-use-versions-from-resolved-file
