name: SwiftFormat fix and commit

# on: workflow_dispatch

# on:
#   pull_request:
#   push:
#     branches: master

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string

jobs:
  swiftformat:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - name: Install SwiftFormat
      uses: Cyberbeni/install-swift-tool@v3
      with:
        url: https://github.com/nicklockwood/SwiftFormat
        version: ${{ inputs.version }}
    - name: Format
      run: swiftformat .
    - name: Commit
      if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target' || github.event_name == 'workflow_dispatch'
      uses: EndBug/add-and-commit@v9
