name: SwiftFormat lint

# on:
#   pull_request:
#   push:
#     branches: master

on: workflow_call

jobs:
  swiftformat-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install SwiftFormat
      uses: Cyberbeni/install-swift-tool@v2
      with:
        url: https://github.com/nicklockwood/SwiftFormat
        version: '*'
    - name: Lint
      run: swiftformat --lint .
