name: SwiftFormat lint

# on:
#   pull_request:
#   push:
#     branches: master

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string


jobs:
  swiftformat-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install SwiftFormat
      uses: Cyberbeni/install-swift-tool@v3
      with:
        url: https://github.com/nicklockwood/SwiftFormat
        version: ${{ inputs.version }}
    - name: Lint
      run: swiftformat --lint .
