name: Test minimum Swift version

# on:
#   pull_request:

on:
  workflow_call:
    inputs:
      swift-version:
        required: true
        type: string

jobs:
  test-swift-version:
    runs-on: ubuntu-latest
    container:
      image: swift:${{ inputs.swift-version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Check package file
      run: test "// swift-tools-version:${{ inputs.swift-version }}" = "$(head -1 Package.swift)"
    - name: Check build
      run: swift build --configuration release --disable-sandbox
